<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Casts\Attribute;

class LandasanHukum extends Model
{
    use HasFactory;
    protected $fillable = [
        'bidang_id',
        'jenis_peraturan',
        'nomor_peraturan',
        'tahun_peraturan',
        'tentang',
    ];

    public function bidang()
    {
        return $this->belongsTo(Bidang::class);
    }


    protected function jenisPeraturanLengkap(): Attribute
    {
        return new Attribute(
            get: fn () => match ($this->jenis_peraturan) {
                'UU' => 'Undang-Undang',
                'PP' => 'Peraturan Pemerintah',
                'Perpres' => 'Peraturan Presiden',
                'Perda' => 'Peraturan Daerah',
                'Perwal' => 'Peraturan Wali Kota',
                'Kepmen' => 'Keputusan Menteri',
                'Kepres' => 'Keputusan Presiden',
                'Kepwal' => 'Keputusan Wali Kota',
                'Perkada' => 'Peraturan Kepala Daerah',
                'Permen' => 'Peraturan Menteri',
                'Inpres' => 'Instruksi Presiden',
                'Inmen' => 'Instruksi Menteri',
                'SE' => 'Surat Edaran',
                'SK' => 'Surat Keputusan',
                'KEP' => 'Keputusan',
                'Perbup' => 'Peraturan Bupati',
                'Permendagri' => 'Peraturan Menteri Dalam Negeri',
                'Permenkumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenkes' => 'Peraturan Menteri Kesehatan',
                'Permenkeu' => 'Peraturan Menteri Keuangan',
                'Permenhub' => 'Peraturan Menteri Perhubungan',
                'Permenpu' => 'Peraturan Menteri Pekerjaan Umum',
                'Permenpanrb' => 'Peraturan Menteri Pendayagunaan Aparatur Negara Dan Reformasi Birokrasi',
                'Permenesdm' => 'Peraturan Menteri Energi Dan Sumber Daya Mineral',
                'Permenlh' => 'Peraturan Menteri Lingkungan Hidup',
                'Permenpora' => 'Peraturan Menteri Pemuda Dan Olahraga',
                'Permenkominfo' => 'Peraturan Menteri Komunikasi Dan Informatika',
                'Permenhukum' => 'Peraturan Menteri Hukum',
                'Permen' => 'Peraturan Menteri',
                'Permendikbud' => 'Peraturan Menteri Pendidikan Dan Kebudayaan',
                'Permendiknas' => 'Peraturan Menteri Pendidikan Nasional',
                'Permendikti' => 'Peraturan Menteri Pendidikan Tinggi',
                'Permendik' => 'Peraturan Menteri Pendidikan',
                'Permendag' => 'Peraturan Menteri Perdagangan',
                'Permenperin' => 'Peraturan Menteri Perindustrian',
                'Permenkop' => 'Peraturan Menteri Koperasi',
                'Permenpan' => 'Peraturan Menteri Pendayagunaan Aparatur Negara',
                'Permenpupr' => 'Peraturan Menteri Pekerjaan Umum Dan Perumahan Rakyat',
                'Permenrin' => 'Peraturan Menteri Perindustrian',
                'Permenkum' => 'Peraturan Menteri Hukum',
                'Permenhukumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenhukum' => 'Peraturan Menteri Hukum',
                'Permenkominfo' => 'Peraturan Menteri Komunikasi Dan Informatika',
                'Permenpanrb' => 'Peraturan Menteri Pendayagunaan Aparatur Negara Dan Reformasi Birokrasi',
                'Permenpan' => 'Peraturan Menteri Pendayagunaan Aparatur Negara',
                'Permenpupr' => 'Peraturan Menteri Pekerjaan Umum Dan Perumahan Rakyat',
                'Permenkeu' => 'Peraturan Menteri Keuangan',
                'Permenkes' => 'Peraturan Menteri Kesehatan',
                'Permenesdm' => 'Peraturan Menteri Energi Dan Sumber Daya Mineral',
                'Permenlh' => 'Peraturan Menteri Lingkungan Hidup',
                'Permenpora' => 'Peraturan Menteri Pemuda Dan Olahraga',
                'Permenkop' => 'Peraturan Menteri Koperasi',
                'Permenperin' => 'Peraturan Menteri Perindustrian',
                'Permenrin' => 'Peraturan Menteri Perindustrian',
                'Permenkumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenkum' => 'Peraturan Menteri Hukum',
                'Permenhukumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenhukum' => 'Peraturan Menteri Hukum',
                'Permenkominfo' => 'Peraturan Menteri Komunikasi Dan Informatika',
                'Permenpanrb' => 'Peraturan Menteri Pendayagunaan Aparatur Negara Dan Reformasi Birokrasi',
                'Permenpan' => 'Peraturan Menteri Pendayagunaan Aparatur Negara',
                'Permenpupr' => 'Peraturan Menteri Pekerjaan Umum Dan Perumahan Rakyat',
                'Permenkeu' => 'Peraturan Menteri Keuangan',
                'Permenkes' => 'Peraturan Menteri Kesehatan',
                'Permenesdm' => 'Peraturan Menteri Energi Dan Sumber Daya Mineral',
                'Permenlh' => 'Peraturan Menteri Lingkungan Hidup',
                'Permenpora' => 'Peraturan Menteri Pemuda Dan Olahraga',
                'Permenkop' => 'Peraturan Menteri Koperasi',
                'Permenperin' => 'Peraturan Menteri Perindustrian',
                'Permenrin' => 'Peraturan Menteri Perindustrian',
                'Permenkumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenkum' => 'Peraturan Menteri Hukum',
                'Permenhukumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenhukum' => 'Peraturan Menteri Hukum',
                'Permenkominfo' => 'Peraturan Menteri Komunikasi Dan Informatika',
                'Permenpanrb' => 'Peraturan Menteri Pendayagunaan Aparatur Negara Dan Reformasi Birokrasi',
                'Permenpan' => 'Peraturan Menteri Pendayagunaan Aparatur Negara',
                'Permenpupr' => 'Peraturan Menteri Pekerjaan Umum Dan Perumahan Rakyat',
                'Permenkeu' => 'Peraturan Menteri Keuangan',
                'Permenkes' => 'Peraturan Menteri Kesehatan',
                'Permenesdm' => 'Peraturan Menteri Energi Dan Sumber Daya Mineral',
                'Permenlh' => 'Peraturan Menteri Lingkungan Hidup',
                'Permenpora' => 'Peraturan Menteri Pemuda Dan Olahraga',
                'Permenkop' => 'Peraturan Menteri Koperasi',
                'Permenperin' => 'Peraturan Menteri Perindustrian',
                'Permenrin' => 'Peraturan Menteri Perindustrian',
                'Permenkumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenkum' => 'Peraturan Menteri Hukum',
                'Permenhukumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenhukum' => 'Peraturan Menteri Hukum',
                'Permenkominfo' => 'Peraturan Menteri Komunikasi Dan Informatika',
                'Permenpanrb' => 'Peraturan Menteri Pendayagunaan Aparatur Negara Dan Reformasi Birokrasi',
                'Permenpan' => 'Peraturan Menteri Pendayagunaan Aparatur Negara',
                'Permenpupr' => 'Peraturan Menteri Pekerjaan Umum Dan Perumahan Rakyat',
                'Permenkeu' => 'Peraturan Menteri Keuangan',
                'Permenkes' => 'Peraturan Menteri Kesehatan',
                'Permenesdm' => 'Peraturan Menteri Energi Dan Sumber Daya Mineral',
                'Permenlh' => 'Peraturan Menteri Lingkungan Hidup',
                'Permenpora' => 'Peraturan Menteri Pemuda Dan Olahraga',
                'Permenkop' => 'Peraturan Menteri Koperasi',
                'Permenperin' => 'Peraturan Menteri Perindustrian',
                'Permenrin' => 'Peraturan Menteri Perindustrian',
                'Permenkumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenkum' => 'Peraturan Menteri Hukum',
                'Permenhukumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenhukum' => 'Peraturan Menteri Hukum',
                'Permenkominfo' => 'Peraturan Menteri Komunikasi Dan Informatika',
                'Permenpanrb' => 'Peraturan Menteri Pendayagunaan Aparatur Negara Dan Reformasi Birokrasi',
                'Permenpan' => 'Peraturan Menteri Pendayagunaan Aparatur Negara',
                'Permenpupr' => 'Peraturan Menteri Pekerjaan Umum Dan Perumahan Rakyat',
                'Permenkeu' => 'Peraturan Menteri Keuangan',
                'Permenkes' => 'Peraturan Menteri Kesehatan',
                'Permenesdm' => 'Peraturan Menteri Energi Dan Sumber Daya Mineral',
                'Permenlh' => 'Peraturan Menteri Lingkungan Hidup',
                'Permenpora' => 'Peraturan Menteri Pemuda Dan Olahraga',
                'Permenkop' => 'Peraturan Menteri Koperasi',
                'Permenperin' => 'Peraturan Menteri Perindustrian',
                'Permenrin' => 'Peraturan Menteri Perindustrian',
                'Permenkumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenkum' => 'Peraturan Menteri Hukum',
                'Permenhukumham' => 'Peraturan Menteri Hukum Dan Ham',
                'Permenhukum' => 'Peraturan Menteri Hukum',
                'Permenkominfo' => 'Peraturan Menteri Komunikasi Dan Informatika',
                'Permenpanrb' => 'Peraturan Menteri Pendayagunaan Aparatur Negara Dan Reformasi Birokrasi',
                'Permenpan' => 'Peraturan Menteri Pendayagunaan Aparatur Negara',
                'Permenpupr' => 'Peraturan Menteri Pekerjaan Umum Dan Perumahan Rakyat',
                default => $this->jenis_peraturan,
            }
        );
    }
}
